# Generated by Django 4.2.3 on 2023-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0461_alter_realm_default_code_block_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="preferred_language",
            field=models.CharField(default="en", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="realmuserdefault",
            name="preferred_language",
            field=models.CharField(default="en", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(default="en", max_length=50, null=True),
        ),
    ]