# Generated by Django 4.2.3 on 2023-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0462_realm_preferred_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="translated_content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="translated_content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="scheduledmessage",
            name="translated_content",
            field=models.TextField(null=True),
        ),
    ]
